### ISSUE TITLE
Webwalker Lumbridge null build path

### ISSUE THREAD

**Issue by mswdev** [rs-peer/issues#166] opened 2018-07-30 16:53 UTC
Webwalker returns a null build path on the second floor north stairs of the Lumbridge castle.

![screen shot 2018-07-30 at 10 50 57 am](https://user-images.githubusercontent.com/11341771/43411204-c17b4442-93e6-11e8-8258-6edd4c21bf49.png)

**Comment by SPEN-CER** [comment] 2018-08-01 06:03
Where are you building the path to?

**Comment by Sphiinx** [comment] 2018-08-01 06:04
BankLocation.getNearest();

**Comment by SPEN-CER** [comment] 2018-08-01 06:06
Closed as duplicate of #156

**Closed as completed by SPEN-CER** 2018-08-01 06:06 UTC
