### ISSUE TITLE
Big lag when opening bank

### ISSUE THREAD

**Issue by Man16** [rs-peer/issues#186] opened 2018-08-04 11:04 UTC
Seems to happen with banks that have a lot of items in them.

**Comment by ayzee5793** [comment] 2018-08-04 14:49
It's still having the lag when opening the bank.

**Comment by Jasper-ketelaar** [comment] 2018-08-04 14:55
That version is not live yet.

**Comment by Man16** [comment] 2018-08-05 14:33
Seems to be a lot better for me personally.

**Comment by tfrpp** [comment] 2018-08-05 14:35
@Man16 I just commented here because banking in general is kind of buggy right now. Simple stuff like withdrawing an item is freezing my client for like 3 seconds, the timings all fucked. A script I've used for 150+ hours perfectly is now suddenly opening the bank twice to withdraw items because it takes too long for items to actually enter the inventory, kind of as if I were lagging. But hopping worlds does not change it, and it only happens on the RSP client. When I use official client I have no issues at all.

**Comment by zuzed** [comment] 2018-08-05 14:47
+1 for banking issues, personally also having lag whenever dropping a full inventory. Bad enough the bot will d/c and reconnect. I know its something with the latest version, can drop fine on official client but I cant even manually drop on rspeer.

**Comment by MadDevelop** [comment] 2018-08-05 14:53
I'm looking into it now, I can't reproduce it so its a bit hard to see if its happening :(

**Comment by Man16** [comment] 2018-08-05 14:54
@MadDevelop Make sure you got a bunch of items in your bank

**Comment by MadDevelop** [comment] 2018-08-05 14:54
How many?

**Comment by Man16** [comment] 2018-08-05 14:55
The more you have, the better. Around 800 items in bank is maxium I think. You could try with around 400-500

**Comment by tfrpp** [comment] 2018-08-05 14:56
@MadDevelop I have a filled 580 out of 816 slots in my bank. Game is in fixed screen on OSX if that matters.

**Comment by MadDevelop** [comment] 2018-08-05 14:57
Ahh i only have like 4 items, could I use one of your guys accounts? Just PM me on discord if so.

**Comment by MadDevelop** [comment] 2018-08-05 15:07
@tfrpp What client version are you running? Check top left on bot client.

**Comment by tfrpp** [comment] 2018-08-05 15:09
@MadDevelop it says 1.0

**Comment by Man16** [comment] 2018-08-05 15:24
The problem might be that you are not allocating memory limit to it?

**Comment by ayzee5793** [comment] 2018-08-05 15:29
I am experiencing the same issue if it helps. Literally makes the game DC at times at the bank.

**Comment by MadDevelop** [comment] 2018-08-05 15:39
@ayzee5793 Can you PM me on discord, i'd like to give you another jar to try.

**Comment by MadDevelop** [comment] 2018-08-05 16:11
This has been fixed in the latest bot update, please let me know if this is still happening or not. Closing for now.

**Closed as completed by MadDevelop** 2018-08-05 16:11 UTC
