### ISSUE TITLE
The web tries to switch Varrock teleport location without the requirement to do so

### ISSUE THREAD

**Issue by troys-code** [rs-peer/issues#227] opened 2018-08-16 20:30 UTC
http://oldschoolrunescape.wikia.com/wiki/Varrock_Diary#Rewards_2
* Ability to switch the Varrock Teleport destination to the Grand Exchange by right clicking the spell icon in the Spellbook interface

Web walking tries to use this when you haven't completed the hard varrock diary. It should only do this if you have the requirements met, and it is better to teleport to the other location.

**Comment by Sphiinx** [comment] 2018-08-16 20:33
I believe this is because you have to open the magic tab at least once otherwise, this will happen.

@SPEN-CER Is planning on adding a shadow-opening to fix this.

Duplicate of #208

**Closed as completed** 2019-01-14 19:04 UTC
