### ISSUE TITLE
Interacting with UI whilst script is running causes clicks to not go to the game canvas.

### ISSUE THREAD

**Issue by Man16** [rs-peer/issues#76] opened 2018-07-08 09:39 UTC
How to reproduce:

Have script do random stuff
Open settings menu and when the script tries to click, the menu will close and no action will occur within the game.

**Comment by SPEN-CER** [comment] 2018-07-08 13:11
Closed as duplicate of #6

**Closed as completed by SPEN-CER** 2018-07-08 13:11 UTC
Labels: duplicate
